node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'NodeJS') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v2/', '71b3e8e4-26ad-4be5-9503-7d1627693202') {
       def app = docker.build("jutilisedocker1/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
